USE QLSV;
GO

-- TẠO BẢNG KHOA
CREATE TABLE KHOA(
  MAKHOA NVARCHAR(10) PRIMARY KEY,
  TENKHOA NVARCHAR(50) NOT NULL
);
GO

-- TẠO BẢNG BỘ MÔN
CREATE TABLE BOMON (
  MABOMON NVARCHAR(10) PRIMARY KEY,
  TENBOMON NVARCHAR(100) NOT NULL,  
  MAKHOA NVARCHAR(10) FOREIGN KEY REFERENCES KHOA(MAKHOA)
);
GO

-- TẠO BẢNG GIÁO VIÊN
CREATE TABLE GIAOVIEN (
  MAGIAOVIEN NVARCHAR(10) PRIMARY KEY,
  HOTEN NVARCHAR(100) NOT NULL,
  NGAYSINH DATE NOT NULL,
  MABOMON NVARCHAR(10) FOREIGN KEY REFERENCES BOMON(MABOMON)
);
GO

-- TẠO BẢNG MÔN HỌC
CREATE TABLE MONHOC(
  MAMON NVARCHAR(10) PRIMARY KEY,
  TENMON NVARCHAR(100) NOT NULL,
  SOTINCHI INT NOT NULL
);
GO

-- TẠO BẢNG LỚP
CREATE TABLE LOP(
  MALOP NVARCHAR(10) PRIMARY KEY,
  TENLOP NVARCHAR(100) NOT NULL
);
GO

-- TẠO BẢNG LỚP HỌC PHẦN
CREATE TABLE LOPHOCPHAN(  
  MALOPHOCPHAN NVARCHAR(10) PRIMARY KEY,
  TENLOPHOCPHAN NVARCHAR(100) NOT NULL,
  HOCKI INT NOT NULL,
  MAMON NVARCHAR(10) FOREIGN KEY REFERENCES MONHOC(MAMON), 
  MAGIAOVIEN NVARCHAR(10) FOREIGN KEY REFERENCES GIAOVIEN(MAGIAOVIEN)
);
GO

-- TẠO BẢNG SINH VIÊN
CREATE TABLE SINHVIEN(
  MASINHVIEN NVARCHAR(13) PRIMARY KEY,
  HOTEN NVARCHAR(100) NOT NULL,
  NGAYSINH DATE NOT NULL
);
GO

-- TẠO BẢNG LỚP SINH VIÊN
CREATE TABLE LOPSINHVIEN(
  MALOP NVARCHAR(10),
  MASINHVIEN NVARCHAR(13),
  CHUCVU NVARCHAR(50),
  PRIMARY KEY (MALOP, MASINHVIEN),
  FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
  FOREIGN KEY (MASINHVIEN) REFERENCES SINHVIEN(MASINHVIEN)
);
GO

-- TẠO BẢNG GIÁO VIÊN CHỦ NHIỆM
CREATE TABLE GIAOVIENCHUNHIEM(
  MALOP NVARCHAR(10),
  MAGIAOVIEN NVARCHAR(10),
  HOCKI INT,
  PRIMARY KEY (MALOP, MAGIAOVIEN, HOCKI),
  FOREIGN KEY (MALOP) REFERENCES LOP(MALOP),
  FOREIGN KEY (MAGIAOVIEN) REFERENCES GIAOVIEN(MAGIAOVIEN)
);
GO

-- TẠO BẢNG ĐĂNG KÝ MÔN HỌC (CÓ CỘT TỰ ĐỘNG TÍNH ĐIỂM TỔNG KẾT)
CREATE TABLE DANGKIMONHOC(
  MALOPHOCPHAN NVARCHAR(10),
  MASINHVIEN NVARCHAR(13),
  DIEMTHANHPHAN FLOAT CHECK (DIEMTHANHPHAN BETWEEN 0 AND 10),
  DIEMTHI FLOAT CHECK (DIEMTHI BETWEEN 0 AND 10),
  PHANTRAMTHI FLOAT CHECK (PHANTRAMTHI BETWEEN 0 AND 100),
  DIEMTONGKET AS (DIEMTHANHPHAN * 0.4 + DIEMTHI * 0.6),
  PRIMARY KEY (MALOPHOCPHAN, MASINHVIEN),
  FOREIGN KEY (MALOPHOCPHAN) REFERENCES LOPHOCPHAN(MALOPHOCPHAN), 
  FOREIGN KEY (MASINHVIEN) REFERENCES SINHVIEN(MASINHVIEN)
);
GO
