SELECT ROW_NUMBER() OVER (ORDER BY MAKHOA ASC) AS STT, * FROM KHOA;

SELECT ROW_NUMBER() OVER (ORDER BY MABOMON ASC, MAKHOA ASC) AS STT, * FROM BOMON;

SELECT ROW_NUMBER() OVER (ORDER BY MAGIAOVIEN ASC) AS STT, * FROM GIAOVIEN;

SELECT ROW_NUMBER() OVER (ORDER BY MAMON ASC) AS STT, * FROM MONHOC;

SELECT ROW_NUMBER() OVER (ORDER BY MALOP ASC) AS STT, * FROM LOP;

SELECT ROW_NUMBER() OVER (ORDER BY MALOPHOCPHAN ASC, MAMON ASC) AS STT, * FROM LOPHOCPHAN;

SELECT ROW_NUMBER() OVER (ORDER BY MASINHVIEN ASC) AS STT, * FROM SINHVIEN;

SELECT ROW_NUMBER() OVER (ORDER BY MALOP ASC, MASINHVIEN ASC) AS STT, * FROM LOPSINHVIEN;

SELECT ROW_NUMBER() OVER (ORDER BY MALOP ASC, MAGIAOVIEN ASC, HOCKI ASC) AS STT, * FROM GIAOVIENCHUNHIEM;

SELECT ROW_NUMBER() OVER (ORDER BY MALOPHOCPHAN ASC, MASINHVIEN ASC) AS STT, * FROM DANGKIMONHOC;
